<?php


class PruebaTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::table('users')->where('email','test@gmail.com')->delete();

    }

    /**
     * A basic test example.
     *
     * @return void
     */
  
    public function testConection(){
        try{
            DB::connection('mysql')->getDatabaseName();
        }catch(PDOException $e){
            $this->assertNotTrue(true);
        }
        $this->assertTrue(true);


    }
}
