<?php


class PruebaTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::table('users')->where('email','test@gmail.com')->delete();

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testRegister()
    {
        $this->visit('/register')
            ->type('Test','name')
            ->type('test@gmail.com','email')
            ->type('secret','password')
            ->type('secret','password_confirmation')
            ->press('Register')
            ->seePageIs('/home');
    }

    public function testLogin(){
        $this->visit('/login')
            ->type('test@gmail.com','email')
            ->type('secret','password')
            ->check('remember')
            ->press('Login')
            ->see('Test');
    }

    public function testConection(){
        try{
            DB::connection('mysql')->getDatabaseName();
        }catch(PDOException $e){
            $this->assertNotTrue(true);
        }
        $this->assertTrue(true);


    }
}
